version: "3.7"

services:
  postgres:
    build: ./postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db

  rest-api:
    build: ../
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: dev
      JAVA_HEAP_SIZE_MB: 2048
